<ul class="nav nav-pills nav-stacked" role="tablist">
  <li role="presentation" class="active"><a href="/business/shops/list" data-toggle="collapse">商家管理</a>
  	<ul class="nav nav-pills nav-stacked collapse " role="tablist">
	  <li role="presentation" class=""><a href="/business/shops/list">商家管理</a></li>
	  <li role="presentation"><a href="#">用户管理</a></li>
	  <li role="presentation"><a href="#">订单管理</a></li>
	</ul>
  </li>
  <li role="presentation"><a href="#">用户管理</a></li>
  <li role="presentation"><a href="#">订单管理</a></li>
</ul>
