<h1>添加</h1>
<?php echo $this->tag->form(['business/shops/save','id'=>'add-shops','method'=>'post','onbeforesubmit'=> 'return false']);?>
    <p>
        <label>Name</label>
        <?php echo $form->render("name",array('maxlength' => 30, 'placeholder' => 'Type your name','class'=>'form-control txt-name') ) ?>
    </p>

    <p>
        <div class="control-group">
            <?php echo $form->get('username')->getLabel();?>
            <div class="controls">
                <?php echo $form->render("username",['class'=>'form-control txt-name'])?>
                <p class="help-block">(required)</p>
                <div class="alert alert-warning" id="name_alert">
                    <strong>Warning!</strong> Please enter your full name
                </div>
            </div>
        </div>
    </p>

    <p>
        <label>Type</label>
        <?php echo $form->render("email") ?>
    </p>

    <p>
        <input type="submit" value="Save" />
    </p>

</form>